version=0.26.0

description=SDK for publishing metrics to faststats.dev
license=MIT License
license_url=https://github.com/faststats-dev/faststats-java/blob/main/LICENSE
author=FastStats Team
author_id=faststats-dev
author_url=https://github.com/faststats-dev
github_url=https://github.com/Matthiesen-dev/libs
git_url=github.com/Matthiesen-dev/libs.git