name: FastStats Shadow Release

on:
  workflow_dispatch:
    inputs:
        version:
            description: 'Version to build'
            required: true
            default: '0.26.0'

jobs:
  run:
    uses: matthiesen-dev/automation/.github/workflows/libs-gradle-task.yml@main
    with:
      project_name: "faststats"
      version: ${{ github.event.inputs.version }}
    secrets:
      maven_username: ${{ secrets.ORG_GRADLE_PROJECT_DEVMATTHIESENMAVENUSERNAME }}
      maven_password: ${{ secrets.ORG_GRADLE_PROJECT_DEVMATTHIESNMAVENPASSWORD }}
